version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example # Use postgres/example user/password credentials

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
