apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        network/mailer-micro-service-default: "true"
        service: app
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:16.1
          command: ['sh', '-c',
            'until pg_isready -h postgres -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - args:
            - /usr/local/bin/mailer-micro-service
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
          image: mailer-micro-service-app
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
