apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build=local
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/mailer-micro-service-default: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: example
          image: postgres:16.1
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      restartPolicy: Always
      volumes:
        - name: init-db
          configMap:
            name: postgres-initdb-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
